### ISSUE TITLE
Community Dockers - Studio and Portal

### ISSUE THREAD

**Issue by smcpoland** [Bonitasoft-Community/docker_bonita#1]
If there is one thing I really find quite annoying it's when i have to shutdown and restart my various Bonita's.

Some developed assets are in 6.5.0, 6.5.1 7.0.0 7.02 etc.  

What i would like to see is a co-ordinated versioning of Bonita in Docker so we, the developers, can have multiple versions of Bonita running at the same time.  It would surely help with our support options as well.

Before anyone says - not possible because of memory etc. Some of us use servers as our desktop, while others use normal PC's and with the newer Intel chips able to support 64GB RAM this will not be an issue.

Even my laptop has 16GB RAM so could run a couple of dockers at the same time...

This type of customization is way beyond me, but I put it forward as the future of development Bonita, all in Docker.

Imagine, 6.5.0, 7.0.3 and two corresponding portals running side by side, no issues with sharing one database either.  Wow. :)

regards

**Comment by JeremJR** [comment]
Hi,

Sorry for the late response. I have created a Dockerfile to help you in a new repo https://github.com/Bonitasoft-Community/docker_bonita_studio
Feel free to improve it.
If you have questions regarding it, please open issue directly on this new repo.

Regards,
Jérémy
