### ISSUE TITLE
Getting error when starting container (./setup/setup.sh: Permission denied)

### ISSUE THREAD

**Issue by stijni** [Bonitasoft-Community/docker_bonita#18]
Hi,

Just installed a blank Ubuntu 18.04. 
Installed docker.io and docker-compose
Ran docker run --name bonita -d -p 8080:8080 bonita and I get the error Permission denied.
Any idea?
Thanks

**Comment by JeremJR** [comment]
Hi,
Thank you for reporting this issue.
I proposed this fix https://github.com/Bonitasoft-Community/docker_bonita/pull/20 
That should solve your issue once reviewed and pushed to the docker library.
Regards,
Jérémy

**Comment by stijni** [comment]
Works great. Thanks
