### ISSUE TITLE
"exec: \"/opt/files/startup.sh\": permission denied": unknown

### ISSUE THREAD

**Issue by jessie-z** [Bonitasoft-Community/docker_bonita#19]
[Command] docker run --name bonita bonita

[Command Output]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/opt/files/startup.sh\": permission denied": unknown.
ERRO[0000] error waiting for container: context canceled

**Comment by JeremJR** [comment]
Hi,
Thank you for reporting this issue.
As it seems a duplicate of https://github.com/Bonitasoft-Community/docker_bonita/issues/18 I will close this one.
Please follow https://github.com/Bonitasoft-Community/docker_bonita/issues/18 resolution.
Regards,
Jérémy
