### ISSUE TITLE
Fails with "./setup/setup.sh: Permission denied" on Debian 8

### ISSUE THREAD

**Issue by ghost** [Bonitasoft-Community/docker_bonita#9]
I tried this for a while on our server (Debian GNU/Linux 8.10 (jessie)) and despite everything I tried I always got that error.
Then I tried it on my local machine (Ubuntu 17.10) and it ran perfectly.
The docker logs show
```
+ cd /opt/bonita/BonitaCommunity-7.6.1-Tomcat-8.5.23
+ echo y
+ ./setup/setup.sh init
/opt/files/config.sh: line 153: ./setup/setup.sh: Permission denied
+ ./setup/setup.sh configure
/opt/files/config.sh: line 154: ./setup/setup.sh: Permission denied
```

It doesn't appear (to me) to be related but this is using the MySql options shown in the Docker information.
At one point I tried running a container interactively and stepping through the startup commands, but as far as I could tell the permissions appeared to be correct, along with the user & group.

Any suggestions would be appreciated.
Thanks,
Darren.

**Comment by alarreine** [comment]
Hi,
I have tried with the same configuration: `Debian GNU/Linux 8.10 (jessie)`, `Mysql` and `bonita:lasted` docker image, and I did not have any problem.
Can you give me more details about this issue?

Thanks,
Agustin

**Comment by ghost** [comment]
Hmm, it seems our data drive where the Docker files are, is mounted noexec.
Thanks for ruling out any issues with jessie, it helped me track down the reason.

I grabbed the Dockerfile and updated config.sh and startup.sh, adding a /bin/bash to script calls, and it seems to be working.

Thanks again,
Darren.
